spring.application.name=wahlomat
spring.profiles.active=dev   


# spring.datasource.url=${DB_URL}
# spring.datasource.username=${DB_USERNAME}
# spring.datasource.password=${DB_PASSWORD}

spring.datasource.url=jdbc:postgresql://psql.f4.htw-berlin.de:5432/wahlomat_htw
spring.datasource.username=wahlomat_htw_team2
spring.datasource.password=Z5q8gJFJL

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ADMIN_PASSWORD=${ADMIN_PASSWORD}
ADMIN_PASSWORD=wahlomat2025!

# JWT Configuration
security.jwt.enabled=true

